name: quicat
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=24.2
  - pip:
      - ahocorasick-rs==0.22.0
      - anndata==0.10.9
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - array-api-compat==1.8
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - comm==0.2.2
      - debugpy==1.8.5
      - decorator==5.1.1
      - defusedxml==0.7.1
      - exceptiongroup==1.2.2
      - executing==2.0.1
      - fastjsonschema==2.20.0
      - flpc==0.2.4
      - fqdn==1.5.1
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httpx==0.27.2
      - ipykernel==6.29.5
      - ipython==8.26.0
      - isoduration==20.11.0
      - jedi==0.19.1
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - legacy-api-wrap==1.4
      - llvmlite==0.43.0
      - matplotlib-inline==0.1.7
      - matplotlib-venn==1.1.1
      - mistune==3.0.2
      - natsort==8.4.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.26.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - patsy==0.5.6
      - pexpect==4.9.0
      - platformdirs==4.2.2
      - polars==1.1.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==17.0.0
      - pyfastx==2.1.0
      - pynndescent==0.5.13
      - pysam==0.22.1
      - python-json-logger==2.0.7
      - pyzmq==26.2.0
      - quicat=0.1.0
      - rapidfuzz==3.9.4
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.0
      - scanpy==1.10.2
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - session-info==1.0.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - statsmodels==0.14.2
      - stdlib-list==0.10.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.3.0
      - tomli==2.0.1
      - tornado==6.4.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20240821
      - umap-learn==0.5.6
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
